import { Exercise } from '@/types/workout.types';

/**
 * Curated Exercise Catalog Repository.
 * Structured cleanly so it can be pushed/loaded directly from Supabase
 * without modifying UI or domain layer APIs.
 */
export const CURATED_EXERCISE_CATALOG: Exercise[] = [
  // =================== CHEST ===================
  {
    id: 'ex-bench-press',
    name: 'Barbell Bench Press',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Triceps', 'Front Delts'],
    equipmentRequired: 'Barbell',
    difficulty: 'intermediate',
    movementPattern: 'Horizontal Push',
    instructions: [
      'Lie flat on bench with eyes directly under the racked bar.',
      'Retract scapulae and plant feet firmly on the floor.',
      'Grip the bar with hands slightly wider than shoulder width.',
      'Unrack, take a deep breath, and lower bar under control to the lower-chest/sternum with elbows at 45-60°.',
      'Press forcefully upward and slightly back toward the face to full lockout.',
    ],
    cues: [
      'Bend the bar in half to engage lats and lock shoulders.',
      'Maintain continuous leg drive through your heels.',
      'Touch the chest gently; never bounce the barbell.',
    ],
    mistakesToAvoid: [
      'Flaring elbows out at 90 degrees (excessive shoulder impingement risk).',
      'Lifting hips/butt off the bench during heavy presses.',
      'Bouncing the bar off the ribcage.',
    ],
    alternativeExerciseIds: ['ex-db-bench-press', 'ex-incline-db-press', 'ex-pushup', 'ex-cable-fly'],
    targetMusclesDetail: {
      primary: ['Pectoralis Major (Sternal & Clavicular)'],
      secondary: ['Anterior Deltoid', 'Triceps Brachii'],
    },
    muscleGraphicKey: 'chest_pec_major',
    isSystem: true,
  },
  {
    id: 'ex-db-bench-press',
    name: 'Dumbbell Bench Press',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Triceps', 'Front Delts'],
    equipmentRequired: 'Dumbbells',
    difficulty: 'beginner',
    movementPattern: 'Horizontal Push',
    instructions: [
      'Sit on bench holding dumbbells on thighs, kick them back into position as you lie down.',
      'Set shoulders back and down into the bench.',
      'Lower dumbbells with control until thumbs are level with outer chest.',
      'Press upward in a slight converging arc without banging dumbbells at top.',
    ],
    cues: [
      'Keep wrists stacked directly over your elbows.',
      'Feel a deep, controlled stretch across the chest at the bottom.',
    ],
    mistakesToAvoid: [
      'Dropping dumbbells too fast into the bottom stretch.',
      'Banging the weights together at the peak contraction.',
    ],
    alternativeExerciseIds: ['ex-bench-press', 'ex-pushup'],
    targetMusclesDetail: {
      primary: ['Pectoralis Major'],
      secondary: ['Triceps', 'Anterior Deltoid'],
    },
    muscleGraphicKey: 'chest_pec_major',
    isSystem: true,
  },
  {
    id: 'ex-incline-db-press',
    name: 'Incline Dumbbell Press',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Front Delts', 'Triceps'],
    equipmentRequired: 'Dumbbells',
    difficulty: 'intermediate',
    movementPattern: 'Incline Push',
    instructions: [
      'Set incline bench to 30° to 45° angle.',
      'Bring dumbbells to shoulder level with elbows tucked at 45°.',
      'Press weights up in a smooth arc, squeezing upper pecs at the top.',
      'Lower with 2-3 second eccentric tempo.',
    ],
    cues: [
      'Keep shoulder blades pinned to the pad throughout the set.',
      'Drive dumbbells upward and slightly together.',
    ],
    mistakesToAvoid: [
      'Setting bench angle too steep (>45° shifts load to shoulders).',
      'Arching lower back excessively off the incline pad.',
    ],
    alternativeExerciseIds: ['ex-bench-press', 'ex-pushup'],
    targetMusclesDetail: {
      primary: ['Clavicular Pectoralis (Upper Chest)'],
      secondary: ['Anterior Deltoid', 'Triceps Brachii'],
    },
    muscleGraphicKey: 'chest_upper_pec',
    isSystem: true,
  },
  {
    id: 'ex-pushup',
    name: 'Push-Up',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Triceps', 'Core'],
    equipmentRequired: 'Bodyweight',
    difficulty: 'beginner',
    movementPattern: 'Horizontal Push',
    instructions: [
      'Place hands slightly wider than shoulder width on the floor.',
      'Form a rigid plank line from head to heels with glutes and core braced.',
      'Lower chest until approximately 2 inches from the floor.',
      'Push the ground away to return to top position with full protraction.',
    ],
    cues: [
      'Screw your palms into the floor to activate external rotators.',
      'Keep your gaze slightly ahead of your hands, not looking down at toes.',
    ],
    mistakesToAvoid: [
      'Sagging hips or hyperextending the lower back.',
      'Shrugging shoulders into the neck.',
    ],
    alternativeExerciseIds: ['ex-bench-press', 'ex-db-bench-press'],
    targetMusclesDetail: {
      primary: ['Pectoralis Major'],
      secondary: ['Triceps Brachii', 'Core/Rectus Abdominis'],
    },
    muscleGraphicKey: 'chest_pushup',
    isSystem: true,
  },
  {
    id: 'ex-cable-fly',
    name: 'Cable Chest Fly',
    primaryMuscle: 'Chest',
    secondaryMuscles: ['Front Delts'],
    equipmentRequired: 'Cable',
    difficulty: 'beginner',
    movementPattern: 'Isolation',
    instructions: [
      'Set cable pulleys at chest height, grab D-handles, and take a staggered step forward.',
      'With a slight bend in elbows, bring hands together in a wide hugging motion.',
      'Squeeze chest hard for 1 second at peak contraction.',
      'Return to starting stretch with deliberate control.',
    ],
    cues: [
      'Imagine hugging a large barrel.',
      'Keep elbow angle fixed throughout the movement.',
    ],
    mistakesToAvoid: [
      'Turning the fly into a pressing movement by bending and extending elbows.',
      'Letting shoulders roll forward during the stretch phase.',
    ],
    alternativeExerciseIds: ['ex-pushup', 'ex-db-bench-press'],
    targetMusclesDetail: {
      primary: ['Pectoralis Major (Sternal Head)'],
      secondary: ['Anterior Deltoid'],
    },
    muscleGraphicKey: 'chest_fly',
    isSystem: true,
  },

  // =================== BACK ===================
  {
    id: 'ex-deadlift',
    name: 'Conventional Deadlift',
    primaryMuscle: 'Back',
    secondaryMuscles: ['Hamstrings', 'Glutes', 'Traps'],
    equipmentRequired: 'Barbell',
    difficulty: 'advanced',
    movementPattern: 'Hinge',
    instructions: [
      'Stand with feet hip-width apart, barbell cutting across mid-foot.',
      'Hinge hips back and grip the bar just outside your shins.',
      'Bring shins to touch the bar without pushing it forward.',
      'Pull chest tall, pull slack out of the barbell, and brace core.',
      'Push the floor away through midfoot and stand up to full hip lockout.',
    ],
    cues: [
      'Protect your armpits: imagine squeezing oranges under your arms.',
      'Push the floor away with your legs rather than pulling with your back.',
      'Lock hips and knees simultaneously at the top.',
    ],
    mistakesToAvoid: [
      'Rounding the lumbar spine under load.',
      'Jerking the bar off the floor without removing slack.',
      'Hyperextending the lower back at the top.',
    ],
    alternativeExerciseIds: ['ex-rdl'],
    targetMusclesDetail: {
      primary: ['Erector Spinae', 'Latissimus Dorsi'],
      secondary: ['Hamstrings', 'Gluteus Maximus', 'Trapezius'],
    },
    muscleGraphicKey: 'back_deadlift',
    isSystem: true,
  },
  {
    id: 'ex-barbell-row',
    name: 'Barbell Bent-Over Row',
    primaryMuscle: 'Back',
    secondaryMuscles: ['Biceps', 'Rear Delts'],
    equipmentRequired: 'Barbell',
    difficulty: 'intermediate',
    movementPattern: 'Horizontal Pull',
    instructions: [
      'Hinge at the hips until torso is around 45° angle to the floor with knees soft.',
      'Hold barbell with overhand grip slightly wider than shoulder width.',
      'Pull barbell smoothly to lower sternum/belly button by driving elbows back.',
      'Squeeze shoulder blades together at the top, then lower with control.',
    ],
    cues: [
      'Drive through your elbows, not your hands.',
      'Keep your torso angle steady; avoid bobbing up and down with momentum.',
    ],
    mistakesToAvoid: [
      'Standing too upright (turns it into an upright row/shrug).',
      'Rounding lower back or letting shoulders collapse forward.',
    ],
    alternativeExerciseIds: ['ex-seated-cable-row', 'ex-lat-pulldown'],
    targetMusclesDetail: {
      primary: ['Latissimus Dorsi', 'Rhomboids'],
      secondary: ['Biceps Brachii', 'Posterior Deltoid'],
    },
    muscleGraphicKey: 'back_row',
    isSystem: true,
  },
  {
    id: 'ex-lat-pulldown',
    name: 'Lat Pulldown',
    primaryMuscle: 'Back',
    secondaryMuscles: ['Biceps', 'Rear Delts'],
    equipmentRequired: 'Cable',
    difficulty: 'beginner',
    movementPattern: 'Vertical Pull',
    instructions: [
      'Sit comfortably with thigh pads securely braced over your knees.',
      'Grip wide bar with an overhand grip slightly outside shoulder width.',
      'Arch upper chest slightly upward and pull bar down toward upper collarbone.',
      'Pause at bottom contraction, then resist bar back up to full overhead stretch.',
    ],
    cues: [
      'Lead with elbows pulling straight down toward your back pockets.',
      'Keep your chest high and proud.',
    ],
    mistakesToAvoid: [
      'Leaning excessively backward to swing the weight down.',
      'Pulling the bar behind the neck (dangerous shoulder stress).',
    ],
    alternativeExerciseIds: ['ex-barbell-row', 'ex-seated-cable-row'],
    targetMusclesDetail: {
      primary: ['Latissimus Dorsi'],
      secondary: ['Biceps Brachii', 'Teres Major'],
    },
    muscleGraphicKey: 'back_lat_pulldown',
    isSystem: true,
  },
  {
    id: 'ex-seated-cable-row',
    name: 'Seated Cable Row',
    primaryMuscle: 'Back',
    secondaryMuscles: ['Biceps', 'Rhomboids'],
    equipmentRequired: 'Cable',
    difficulty: 'beginner',
    movementPattern: 'Horizontal Pull',
    instructions: [
      'Sit on bench with feet braced on footrests and knees slightly bent.',
      'Grip V-handle or straight bar with arms extended and spine neutral.',
      'Pull handle toward lower abdomen while retracting shoulder blades.',
      'Pause for 1 second, then control weight back to full stretch without rounding lower back.',
    ],
    cues: [
      'Initiate pull by pinching shoulder blades together.',
      'Keep shoulders depressed away from your ears.',
    ],
    mistakesToAvoid: [
      'Using excessive torso momentum and rocking back and forth.',
      'Locking out knees completely.',
    ],
    alternativeExerciseIds: ['ex-barbell-row', 'ex-lat-pulldown'],
    targetMusclesDetail: {
      primary: ['Rhomboids', 'Middle Trapezius', 'Latissimus Dorsi'],
      secondary: ['Biceps Brachii', 'Posterior Deltoid'],
    },
    muscleGraphicKey: 'back_seated_row',
    isSystem: true,
  },

  // =================== SHOULDERS ===================
  {
    id: 'ex-overhead-press',
    name: 'Overhead Barbell Press',
    primaryMuscle: 'Shoulders',
    secondaryMuscles: ['Triceps', 'Upper Chest'],
    equipmentRequired: 'Barbell',
    difficulty: 'intermediate',
    movementPattern: 'Vertical Push',
    instructions: [
      'Rack bar at collarbone height, grip just outside shoulder width.',
      'Brace core, squeeze glutes and quads for a rock-solid foundation.',
      'Tilt head slightly back as you press bar straight up, then push head through as bar clears forehead.',
      'Lock out bar directly over midfoot and shoulders.',
      'Lower smoothly back to clavicle.',
    ],
    cues: [
      'Squeeze your glutes hard to protect lower back.',
      'Press straight up; do not allow bar to drift forward.',
    ],
    mistakesToAvoid: [
      'Over-arching lumbar spine into a standing incline bench press.',
      'Flaring wrists backward instead of keeping them vertical.',
    ],
    alternativeExerciseIds: ['ex-lateral-raise'],
    targetMusclesDetail: {
      primary: ['Anterior Deltoid', 'Medial Deltoid'],
      secondary: ['Triceps Brachii', 'Clavicular Pec'],
    },
    muscleGraphicKey: 'shoulder_ohp',
    isSystem: true,
  },
  {
    id: 'ex-lateral-raise',
    name: 'Dumbbell Lateral Raise',
    primaryMuscle: 'Shoulders',
    secondaryMuscles: ['Traps'],
    equipmentRequired: 'Dumbbells',
    difficulty: 'beginner',
    movementPattern: 'Isolation',
    instructions: [
      'Stand tall holding dumbbells at your sides with palms facing inward.',
      'With a slight elbow bend and slight forward torso tilt, raise dumbbells out to sides.',
      'Stop when elbows reach shoulder height.',
      'Lower weights under control with 2-second negative.',
    ],
    cues: [
      'Lead with the elbows, not the wrists.',
      'Pour water from a pitcher at the peak for side delt isolation.',
    ],
    mistakesToAvoid: [
      'Swinging torso or using momentum to toss dumbbells up.',
      'Shrugging traps to initiate movement.',
    ],
    alternativeExerciseIds: ['ex-overhead-press', 'ex-face-pull'],
    targetMusclesDetail: {
      primary: ['Lateral (Side) Deltoid'],
      secondary: ['Upper Trapezius'],
    },
    muscleGraphicKey: 'shoulder_lateral',
    isSystem: true,
  },
  {
    id: 'ex-face-pull',
    name: 'Rear Delt Face Pull',
    primaryMuscle: 'Shoulders',
    secondaryMuscles: ['Upper Back', 'Rotator Cuff'],
    equipmentRequired: 'Cable',
    difficulty: 'beginner',
    movementPattern: 'Horizontal Pull',
    instructions: [
      'Attach rope to upper pulley at eye level.',
      'Grip rope with thumbs facing backwards and step back into tension.',
      'Pull rope toward bridge of nose while externally rotating wrists out and back.',
      'Hold peak contraction for 1 second, then control return.',
    ],
    cues: [
      'Pull hands apart as you reach your face.',
      'Think double bicep pose at the peak.',
    ],
    mistakesToAvoid: [
      'Using too much weight and leaning backward to cheat.',
      'Letting elbows drop below wrists.',
    ],
    alternativeExerciseIds: ['ex-lateral-raise', 'ex-seated-cable-row'],
    targetMusclesDetail: {
      primary: ['Posterior (Rear) Deltoid'],
      secondary: ['Infraspinatus', 'Rhomboids', 'Trapezius'],
    },
    muscleGraphicKey: 'shoulder_face_pull',
    isSystem: true,
  },

  // =================== LEGS ===================
  {
    id: 'ex-squat',
    name: 'Barbell Back Squat',
    primaryMuscle: 'Legs',
    secondaryMuscles: ['Glutes', 'Core'],
    equipmentRequired: 'Barbell',
    difficulty: 'intermediate',
    movementPattern: 'Squat',
    instructions: [
      'Step under barbell resting across upper traps, grip firmly and pull elbows down.',
      'Unrack, take 2-3 decisive steps back, set stance shoulder-width with toes turned out 15-30°.',
      'Inhale deeply into belly to brace core.',
      'Descend by breaking at hips and knees simultaneously until thighs are parallel to the floor.',
      'Drive through midfoot to stand up forcefully.',
    ],
    cues: [
      'Spread the floor with your feet to engage glutes.',
      'Chest tall, knees tracking in line with toes.',
    ],
    mistakesToAvoid: [
      'Knees caving inward (valgus collapse).',
      'Weight shifting onto toes, lifting heels.',
      'Rounding the lower back in the hole (butt wink).',
    ],
    alternativeExerciseIds: ['ex-goblet-squat', 'ex-split-squat'],
    targetMusclesDetail: {
      primary: ['Quadriceps', 'Gluteus Maximus'],
      secondary: ['Hamstrings', 'Adductors', 'Core'],
    },
    muscleGraphicKey: 'legs_squat',
    isSystem: true,
  },
  {
    id: 'ex-rdl',
    name: 'Romanian Deadlift',
    primaryMuscle: 'Legs',
    secondaryMuscles: ['Hamstrings', 'Glutes', 'Lower Back'],
    equipmentRequired: 'Barbell',
    difficulty: 'intermediate',
    movementPattern: 'Hinge',
    instructions: [
      'Stand upright holding barbell at thighs with overhand grip.',
      'Unlock knees with a slight 15-20° bend and freeze that knee angle.',
      'Push hips backward towards wall behind you as bar slides down shins.',
      'Stop when you feel a deep hamstring stretch around mid-shin.',
      'Drive hips forward to return to standing lockout.',
    ],
    cues: [
      'Imagine your hips are a drawer you are pushing shut with your glutes.',
      'Keep the barbell glued to your thighs and shins.',
    ],
    mistakesToAvoid: [
      'Squatting down by bending knees excessively.',
      'Letting the bar drift away from legs.',
    ],
    alternativeExerciseIds: ['ex-deadlift'],
    targetMusclesDetail: {
      primary: ['Hamstrings (Biceps Femoris, Semitendinosus)'],
      secondary: ['Gluteus Maximus', 'Erector Spinae'],
    },
    muscleGraphicKey: 'legs_rdl',
    isSystem: true,
  },
  {
    id: 'ex-goblet-squat',
    name: 'Goblet Squat',
    primaryMuscle: 'Legs',
    secondaryMuscles: ['Quads', 'Core'],
    equipmentRequired: 'Dumbbells',
    difficulty: 'beginner',
    movementPattern: 'Squat',
    instructions: [
      'Hold dumbbell vertically against chest with palms cupping top weight plate.',
      'Set feet shoulder-width apart with toes pointed slightly outward.',
      'Squat down between knees while keeping elbows tucked inside knees.',
      'Drive through heels to return to standing.',
    ],
    cues: [
      'Keep chest tall and proud against the dumbbell.',
      'Use elbows at the bottom to gently push knees out.',
    ],
    mistakesToAvoid: [
      'Letting upper back round forward under the load.',
      'Rising onto balls of feet.',
    ],
    alternativeExerciseIds: ['ex-squat', 'ex-split-squat'],
    targetMusclesDetail: {
      primary: ['Quadriceps'],
      secondary: ['Gluteus Maximus', 'Rectus Abdominis'],
    },
    muscleGraphicKey: 'legs_goblet',
    isSystem: true,
  },
  {
    id: 'ex-split-squat',
    name: 'Bulgarian Split Squat',
    primaryMuscle: 'Legs',
    secondaryMuscles: ['Quads', 'Glutes'],
    equipmentRequired: 'Dumbbells',
    difficulty: 'intermediate',
    movementPattern: 'Lunge',
    instructions: [
      'Stand roughly 2 feet in front of a bench, holding dumbbells at sides.',
      'Place top of rear foot flat on the bench behind you.',
      'Lower hips down until front thigh is parallel to the ground.',
      'Drive through front midfoot/heel to return to standing position.',
    ],
    cues: [
      '75% of your weight remains focused on your front working leg.',
      'Keep a slight forward torso lean to maximize glute engagement.',
    ],
    mistakesToAvoid: [
      'Front foot positioned too close to the bench.',
      'Pushing entirely through rear foot.',
    ],
    alternativeExerciseIds: ['ex-goblet-squat', 'ex-squat'],
    targetMusclesDetail: {
      primary: ['Quadriceps', 'Gluteus Medius & Maximus'],
      secondary: ['Hamstrings', 'Calves'],
    },
    muscleGraphicKey: 'legs_split_squat',
    isSystem: true,
  },
  {
    id: 'ex-calf-raise',
    name: 'Calf Raise',
    primaryMuscle: 'Legs',
    secondaryMuscles: ['Glutes'],
    equipmentRequired: 'Bodyweight',
    difficulty: 'beginner',
    movementPattern: 'Isolation',
    instructions: [
      'Stand on edge of a raised block or step with balls of feet.',
      'Lower heels below step level into a deep calf stretch.',
      'Drive up onto big toes and hold peak contraction for 1 full second.',
      'Lower down smoothly over 3 seconds.',
    ],
    cues: [
      'Do not bounce at the bottom.',
      'Squeeze calves hard at the absolute peak.',
    ],
    mistakesToAvoid: [
      'Rapidly bouncing using Achilles tendon elasticity.',
      'Rolling weight to outside edges of feet.',
    ],
    alternativeExerciseIds: [],
    targetMusclesDetail: {
      primary: ['Gastrocnemius', 'Soleus'],
      secondary: ['Tibialis Posterior'],
    },
    muscleGraphicKey: 'legs_calf',
    isSystem: true,
  },

  // =================== ARMS ===================
  {
    id: 'ex-barbell-curl',
    name: 'Barbell Bicep Curl',
    primaryMuscle: 'Biceps',
    secondaryMuscles: ['Forearms'],
    equipmentRequired: 'Barbell',
    difficulty: 'beginner',
    movementPattern: 'Arm Flexion',
    instructions: [
      'Stand upright holding barbell with underhand shoulder-width grip.',
      'Pin upper arms to your sides.',
      'Curl bar up toward chest by flexing at elbows.',
      'Squeeze biceps at the top, then lower with a controlled 3-second negative.',
    ],
    cues: [
      'Elbows stay glued to your ribs throughout.',
      'Do not swing torso to move the bar.',
    ],
    mistakesToAvoid: [
      'Swinging hips or leaning back to cheat.',
      'Letting elbows drift forward into shoulder flexion.',
    ],
    alternativeExerciseIds: ['ex-hammer-curl'],
    targetMusclesDetail: {
      primary: ['Biceps Brachii (Short & Long Head)'],
      secondary: ['Brachialis', 'Brachioradialis'],
    },
    muscleGraphicKey: 'arms_bicep_curl',
    isSystem: true,
  },
  {
    id: 'ex-hammer-curl',
    name: 'Hammer Curl',
    primaryMuscle: 'Biceps',
    secondaryMuscles: ['Forearms'],
    equipmentRequired: 'Dumbbells',
    difficulty: 'beginner',
    movementPattern: 'Arm Flexion',
    instructions: [
      'Stand holding dumbbells at sides with palms facing each other (neutral grip).',
      'Curl weights upward keeping palms facing each other.',
      'Hold at top for 1 second, then control descent.',
    ],
    cues: [
      'Squeeze dumbbells tightly to activate forearm flexors.',
      'Full extension at the bottom between reps.',
    ],
    mistakesToAvoid: [
      'Flaring elbows out to sides.',
      'Dropping dumbbells rapidly without resistance.',
    ],
    alternativeExerciseIds: ['ex-barbell-curl'],
    targetMusclesDetail: {
      primary: ['Brachialis', 'Brachioradialis'],
      secondary: ['Biceps Brachii'],
    },
    muscleGraphicKey: 'arms_hammer_curl',
    isSystem: true,
  },
  {
    id: 'ex-tricep-pushdown',
    name: 'Tricep Cable Pushdown',
    primaryMuscle: 'Triceps',
    secondaryMuscles: [],
    equipmentRequired: 'Cable',
    difficulty: 'beginner',
    movementPattern: 'Arm Extension',
    instructions: [
      'Attach bar or rope to high cable pulley.',
      'Grip attachment, hinge slightly at hips, and lock elbows at your ribcage.',
      'Extend elbows downward until arms are completely straight.',
      'Squeeze triceps at lockout, then allow forearms to rise back to parallel.',
    ],
    cues: [
      'Keep elbows pinned in place like hinges.',
      'Separate rope ends at bottom lockout for peak tricep contraction.',
    ],
    mistakesToAvoid: [
      'Allowing elbows to swing forward and back with each rep.',
      'Using bodyweight to lean over the bar.',
    ],
    alternativeExerciseIds: ['ex-overhead-tricep-ext'],
    targetMusclesDetail: {
      primary: ['Triceps Brachii (Lateral & Medial Heads)'],
      secondary: ['Anconeus'],
    },
    muscleGraphicKey: 'arms_tricep_pushdown',
    isSystem: true,
  },
  {
    id: 'ex-overhead-tricep-ext',
    name: 'Overhead Dumbbell Tricep Extension',
    primaryMuscle: 'Triceps',
    secondaryMuscles: [],
    equipmentRequired: 'Dumbbells',
    difficulty: 'beginner',
    movementPattern: 'Arm Extension',
    instructions: [
      'Sit or stand holding a dumbbell with both hands overhead in diamond grip.',
      'Keep upper arms close to your head and elbows pointing forward.',
      'Lower dumbbell behind your head by bending at elbows.',
      'Press back up to full overhead lockout.',
    ],
    cues: [
      'Feel the deep stretch along the back of your arms at the bottom.',
      'Keep ribs down and core braced.',
    ],
    mistakesToAvoid: [
      'Flaring elbows out excessively to sides.',
      'Arching lower back heavily.',
    ],
    alternativeExerciseIds: ['ex-tricep-pushdown'],
    targetMusclesDetail: {
      primary: ['Triceps Brachii (Long Head)'],
      secondary: ['Anconeus'],
    },
    muscleGraphicKey: 'arms_tricep_overhead',
    isSystem: true,
  },

  // =================== CORE ===================
  {
    id: 'ex-plank',
    name: 'Plank',
    primaryMuscle: 'Core',
    secondaryMuscles: ['Shoulders', 'Glutes'],
    equipmentRequired: 'Bodyweight',
    difficulty: 'beginner',
    movementPattern: 'Anti-Extension',
    instructions: [
      'Rest on forearms with elbows directly under shoulders.',
      'Extend legs back on toes, body forming a straight line from head to heels.',
      'Tuck pelvis slightly (posterior pelvic tilt) and squeeze glutes and abs maximally.',
      'Breathe steadily through nose while maintaining tension.',
    ],
    cues: [
      'Pull elbows toward toes without actually moving them.',
      'Squeeze glutes as hard as possible.',
    ],
    mistakesToAvoid: [
      'Sagging hips toward the floor.',
      'Piking hips too high in the air.',
    ],
    alternativeExerciseIds: ['ex-leg-raise'],
    targetMusclesDetail: {
      primary: ['Rectus Abdominis', 'Transverse Abdominis'],
      secondary: ['Gluteus Maximus', 'Anterior Deltoid'],
    },
    muscleGraphicKey: 'core_plank',
    isSystem: true,
  },
  {
    id: 'ex-leg-raise',
    name: 'Hanging Leg Raise',
    primaryMuscle: 'Core',
    secondaryMuscles: ['Forearms'],
    equipmentRequired: 'Bodyweight',
    difficulty: 'intermediate',
    movementPattern: 'Spine Flexion',
    instructions: [
      'Hang from a pull-up bar with overhand grip.',
      'Brace core and lift legs or bent knees up until thighs reach 90° or higher.',
      'Curl pelvis up slightly at the top to engage lower abs.',
      'Lower legs under control without swinging.',
    ],
    cues: [
      'Roll your pelvis up toward your sternum.',
      'Stop completely at the bottom before starting the next rep.',
    ],
    mistakesToAvoid: [
      'Using momentum and swinging like a pendulum.',
      'Arching lower back heavily at the bottom.',
    ],
    alternativeExerciseIds: ['ex-plank'],
    targetMusclesDetail: {
      primary: ['Rectus Abdominis (Lower Region)'],
      secondary: ['Iliopsoas (Hip Flexors)', 'Forearm Flexors'],
    },
    muscleGraphicKey: 'core_leg_raise',
    isSystem: true,
  },
  // =================== C8 BODYWEIGHT FOUNDATIONS ===================
  {
    id: 'ex-inverted-row',
    name: 'Inverted Bodyweight Row',
    primaryMuscle: 'Back',
    secondaryMuscles: ['Biceps', 'Forearms', 'Rear Delts'],
    equipmentRequired: 'Bodyweight',
    difficulty: 'beginner',
    movementPattern: 'Horizontal Pull',
    instructions: [
      'Position body under a secure horizontal bar or sturdy table edge.',
      'Grip with hands shoulder-width apart, keeping body in a straight plank.',
      'Pull chest upward toward the anchor point by retracting scapulae.',
      'Lower body with control under eccentric tension.',
    ],
    isSystem: true,
  },
  {
    id: 'ex-doorframe-row',
    name: 'Doorframe Row',
    primaryMuscle: 'Back',
    secondaryMuscles: ['Biceps', 'Forearms'],
    equipmentRequired: 'Bodyweight',
    difficulty: 'beginner',
    movementPattern: 'Horizontal Pull',
    instructions: [
      'Stand facing a sturdy doorframe or vertical pillar.',
      'Grasp the frame firmly at chest height with one or both hands.',
      'Lean backward until arms are extended, bracing core and glutes.',
      'Pull chest toward the frame squeezing the lat and upper back, then lower smoothly.',
    ],
    isSystem: true,
  },
  {
    id: 'ex-superman',
    name: 'Superman',
    primaryMuscle: 'Back',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Lower Back'],
    equipmentRequired: 'Bodyweight',
    difficulty: 'beginner',
    movementPattern: 'Extension',
    instructions: [
      'Lie prone on the floor with arms extended overhead and legs straight.',
      'Simultaneously lift chest, arms, and thighs off the floor.',
      'Hold the peak isometric contraction for 2 to 3 seconds.',
      'Lower slowly to starting position without losing tension.',
    ],
    isSystem: true,
  },
  {
    id: 'ex-pike-pushup',
    name: 'Pike Push-Up',
    primaryMuscle: 'Shoulders',
    secondaryMuscles: ['Triceps', 'Upper Chest', 'Core'],
    equipmentRequired: 'Bodyweight',
    difficulty: 'intermediate',
    movementPattern: 'Vertical Push',
    instructions: [
      'Start in a push-up position, then walk feet forward until hips are elevated in an inverted V shape.',
      'Lower crown of head diagonally forward between your hands.',
      'Press through palms forcefully to lockout, maintaining pike hip angle throughout.',
    ],
    isSystem: true,
  },
  {
    id: 'ex-chair-dips',
    name: 'Chair/Bench Dips',
    primaryMuscle: 'Triceps',
    secondaryMuscles: ['Chest', 'Front Delts'],
    equipmentRequired: 'Bodyweight',
    difficulty: 'beginner',
    movementPattern: 'Vertical Push',
    instructions: [
      'Place palms on the front edge of a stable bench or chair behind your back.',
      'Extend legs forward with heels on the floor.',
      'Lower hips downward by bending elbows until upper arms are parallel to floor.',
      'Press upward through palms to lockout, engaging triceps.',
    ],
    isSystem: true,
  },
  {
    id: 'ex-diamond-pushup',
    name: 'Diamond Push-Up',
    primaryMuscle: 'Triceps',
    secondaryMuscles: ['Chest', 'Front Delts'],
    equipmentRequired: 'Bodyweight',
    difficulty: 'intermediate',
    movementPattern: 'Horizontal Push',
    instructions: [
      'Assume standard push-up position, bringing index fingers and thumbs together under the center of chest.',
      'Keep elbows tucked close to ribcage as you lower chest toward your hands.',
      'Press back up explosively to full extension.',
    ],
    isSystem: true,
  },
  {
    id: 'ex-bw-squat',
    name: 'Bodyweight Squat',
    primaryMuscle: 'Legs',
    secondaryMuscles: ['Glutes', 'Calves', 'Core'],
    equipmentRequired: 'Bodyweight',
    difficulty: 'beginner',
    movementPattern: 'Squat',
    instructions: [
      'Stand upright with feet shoulder-width apart, toes angled slightly out.',
      'Brace core, send hips backward, and bend knees until hip crease dips parallel to knees.',
      'Drive through mid-foot to stand, squeezing glutes at the top.',
    ],
    isSystem: true,
  },
  {
    id: 'ex-glute-bridge',
    name: 'Glute Bridge',
    primaryMuscle: 'Legs',
    secondaryMuscles: ['Hamstrings', 'Lower Back'],
    equipmentRequired: 'Bodyweight',
    difficulty: 'beginner',
    movementPattern: 'Hinge',
    instructions: [
      'Lie on back with knees bent at 90 degrees and feet planted flat on floor.',
      'Drive through heels to lift hips until thighs, hips, and torso form a straight line.',
      'Squeeze glutes firmly at top for 2 seconds before lowering under control.',
    ],
    isSystem: true,
  },
  {
    id: 'ex-reverse-lunge',
    name: 'Reverse Lunge',
    primaryMuscle: 'Legs',
    secondaryMuscles: ['Glutes', 'Hamstrings', 'Core'],
    equipmentRequired: 'Bodyweight',
    difficulty: 'beginner',
    movementPattern: 'Lunge',
    instructions: [
      'Stand tall with feet hip-width apart.',
      'Step backward with one leg and lower back knee until it hovers just above floor.',
      'Keep front shin nearly vertical and torso upright.',
      'Push through front heel to return to starting position, then switch sides.',
    ],
    isSystem: true,
  },
];
