import { gymRepository } from '@/repositories/gym.repository';
import {
  Gym,
  GymAttendanceSession,
  GymMembership,
  MemberGymContextState,
} from '@/types/gym.types';
import { logger } from '@/lib/logger';

export interface CheckInRequest {
  userId: string;
  userRole?: string; // Must be 'member'
  rawQrContent: string;
  expectedGymId?: string; // Current active integrated gym ID
  memberContext?: MemberGymContextState; // Current resolved member context
}

export interface CheckInResult {
  success: boolean;
  session?: GymAttendanceSession;
  gym?: Gym;
  isAlreadyCheckedIn?: boolean;
  error?: string;
}

/**
 * Pure, framework-independent service for Member QR Check-In.
 * Contains zero React/DOM/navigator/localStorage dependencies.
 */
export class GymCheckinService {
  /**
   * Validates and normalizes the canonical FitBoost QR code format.
   * Canonical FitBoost format is the exact string generated by Owner registration:
   * e.g. "fitboost_qr_<slug>_<timestamp36>" or the exact stored qr_code_hash.
   */
  validateQrPayload(rawContent: string): { valid: boolean; qrCodeHash: string; error?: string } {
    if (!rawContent || typeof rawContent !== 'string') {
      return { valid: false, qrCodeHash: '', error: 'Empty or invalid QR content.' };
    }

    const trimmed = rawContent.trim();
    if (!trimmed) {
      return { valid: false, qrCodeHash: '', error: 'Empty QR code.' };
    }

    // Must match the canonical FitBoost format (prefix: fitboost_qr_)
    if (!trimmed.startsWith('fitboost_qr_')) {
      return {
        valid: false,
        qrCodeHash: '',
        error: 'Invalid QR code. Please scan a genuine FitBoost facility QR code.',
      };
    }

    return { valid: true, qrCodeHash: trimmed };
  }

  /**
   * Retrieves any existing active attendance session for the member.
   */
  async getActiveSession(userId: string): Promise<{ session: GymAttendanceSession | null; gym: Gym | null }> {
    if (!userId) return { session: null, gym: null };
    const session = await gymRepository.getActiveAttendanceSession(userId);
    if (!session) return { session: null, gym: null };

    const gym = await gymRepository.fetchGymById(session.gymId);
    return { session, gym };
  }

  /**
   * Main member QR check-in workflow.
   * Performs end-to-end authorization, QR resolution, wrong-gym protection,
   * active session conflict detection, and attendance session creation.
   */
  async checkInWithQr(request: CheckInRequest): Promise<CheckInResult> {
    const { userId, userRole, rawQrContent, expectedGymId, memberContext } = request;

    // 1. Authenticated User & Role Eligibility
    if (!userId || userId === 'guest-user') {
      return { success: false, error: 'You must be signed in to check in.' };
    }

    if (userRole && userRole !== 'member') {
      return {
        success: false,
        error: 'Facility check-in is for athlete members only. Gym owner accounts cannot check in via member flow.',
      };
    }

    // 2. Member Gym Context & Membership Eligibility
    if (memberContext) {
      if (memberContext.mode === 'home') {
        return {
          success: false,
          error: 'You must be enrolled in an integrated gym to check in.',
        };
      }
      if (memberContext.mode === 'non_integrated') {
        return {
          success: false,
          error: 'Personal gyms do not support digital QR check-in.',
        };
      }
      if (memberContext.mode !== 'integrated' || !memberContext.activeGym || !memberContext.activeMembership) {
        return {
          success: false,
          error: 'No active integrated gym found. Please join an integrated gym first.',
        };
      }
      if (memberContext.activeMembership.status !== 'active') {
        const status = memberContext.activeMembership.status;
        if (status === 'pending') {
          return {
            success: false,
            error: 'Your membership request is pending gym approval.',
          };
        }
        if (status === 'frozen') {
          return {
            success: false,
            error: 'Your membership is currently frozen.',
          };
        }
        return {
          success: false,
          error: `Your membership is ${status}. Only active members may check in.`,
        };
      }
    }

    // 3. Active Session Pre-Check (Idempotency barrier 1)
    const existingActive = await gymRepository.getActiveAttendanceSession(userId);
    if (existingActive) {
      const activeGym = await gymRepository.fetchGymById(existingActive.gymId);
      return {
        success: false,
        isAlreadyCheckedIn: true,
        session: existingActive,
        gym: activeGym || undefined,
        error: "You're already checked in.",
      };
    }

    // 4. Validate Canonical QR Payload
    const qrValidation = this.validateQrPayload(rawQrContent);
    if (!qrValidation.valid) {
      return { success: false, error: qrValidation.error };
    }

    // 5. Resolve Gym Identity from QR
    const scannedGym = await gymRepository.resolveGymByQr(qrValidation.qrCodeHash);
    if (!scannedGym) {
      return {
        success: false,
        error: 'Unknown or unrecognized gym QR code. Please ensure you are scanning an official FitBoost QR code.',
      };
    }

    // 6. Wrong Gym Protection
    // Member's active integrated gym must match the scanned gym
    const targetExpectedGymId = expectedGymId || (memberContext && memberContext.activeGym ? memberContext.activeGym.id : null);

    if (targetExpectedGymId && scannedGym.id !== targetExpectedGymId) {
      return {
        success: false,
        error: 'This QR belongs to a different gym. You can only check in to your active integrated gym.',
      };
    }

    // 7. Verify Active Membership for the Scanned Gym
    const membership: GymMembership | null = await gymRepository.getMyGymMembership(scannedGym.id, userId);
    if (!membership) {
      return {
        success: false,
        error: 'You do not have a membership at this gym.',
      };
    }

    if (membership.status !== 'active') {
      if (membership.status === 'pending') {
        return {
          success: false,
          error: 'Your membership request is pending gym approval.',
        };
      }
      if (membership.status === 'frozen') {
        return {
          success: false,
          error: 'Your membership is currently frozen.',
        };
      }
      return {
        success: false,
        error: `Your membership is ${membership.status}. Only active members may check in.`,
      };
    }

    // 8. Canonical Attendance Creation in public.gym_attendance_sessions
    try {
      const result = await gymRepository.startAttendanceSession(
        scannedGym.id,
        userId,
        'qr_scan'
      );

      if (!result.success || !result.session) {
        if (result.error && (result.error.includes("already checked in") || result.error.includes("23505"))) {
          const latestActive = await gymRepository.getActiveAttendanceSession(userId);
          return {
            success: false,
            isAlreadyCheckedIn: true,
            session: latestActive || undefined,
            gym: scannedGym,
            error: "You're already checked in.",
          };
        }
        return {
          success: false,
          error: result.error || 'Failed to start gym visit session.',
        };
      }

      return {
        success: true,
        session: result.session,
        gym: scannedGym,
      };
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : 'Failed to register check-in';
      logger.error('GymCheckinService: Error checking in', { err });
      return {
        success: false,
        error: msg,
      };
    }
  }
}

export const gymCheckinService = new GymCheckinService();
